# Generated by Django 5.2.8 on 2025-11-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='distances',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='speed_kmh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
